version: '3.8'

services:
  matrix-api:
    build: .
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      - NODE_ENV=production
      - MATRIX_MULTI_BACKEND=1
      - MATRIX_PG_URL=postgres://username:password@postgres:5432/matrixdb # Update with your actual credentials
      - MATRIX_WAL_FLUSH_INTERVAL=5000 # Optional: flush interval in ms
    env_file:
      - .env
    command:
      [
        'sh',
        '-c',
        'node dist/src/app/index.cjs --mode api --port 3000 --host 0.0.0.0 --agent /app/memAgent/matrix.yml',
      ]
    volumes:
      - ./memAgent:/app/memAgent:ro # Mount custom agent config
      - matrix-data:/app/.matrix # Persist application data
    restart: unless-stopped
    healthcheck:
      test:
        [
          'CMD',
          'sh',
          '-c',
          'wget --no-verbose --tries=1 --spider http://localhost:3000/health || exit 1',
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
      POSTGRES_DB: testdb
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  matrix-data:
  pgdata:
